name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m playwright install --with-deps

    - name: Lint Python code
      run: |
        pip install flake8
        flake8 auto_resume_agent.py || true

    - name: Dry-run test
      run: |
        python auto_resume_agent.py apply \
          --url "https://example.com/job/123" \
          --profile ./tests/profile.yaml \
          --resume ./tests/resume.txt \
          --dry-run \
          --max-steps 1

    - name: Archive logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-logs
        path: .
